
/* ImageInfo Class
 * Modified: 20 April 2015  
 * Author(s): Phillip Stewart
 * Description:
 *   Stores information for images used in both the menu and game.
 *   Acts as a wrapper for BufferedImage,
 *   ImageInfo objects are tracked by their id.
 *   The ID is an int generated by the constructor and is incremented on
 *   creation of each instance.
 */

import java.awt.image.BufferedImage;

public class ImageInfo {

    /* ===== Members ==========================================================
     * ======================================================================== */
    private BufferedImage img;
    private int x, y;
    private int imgID;
    private boolean show;
    private static int idCounter = 0;

    
    /* ===== Constructor ======================================================
     * ======================================================================== */
    public ImageInfo(BufferedImage I, int X, int Y) {
        ++idCounter;
        this.img = I;
        this.x = X;
        this.y = Y;
        this.show = false;
        this.imgID = idCounter;
    }

    /* ===== Public API ==========================================================
     * ======================================================================== */
    public int getx() {return this.x;}
    public int gety() {return this.y;}
    public int getImgID() {return this.imgID;}
    public BufferedImage getImg() {return this.img;}
    public boolean visible() {return this.show;}
    public void setx(int newX) {this.x = newX;}
    public void sety(int newY) {this.y = newY;}
    public void setImg(BufferedImage newImg) {this.img = newImg;}
    public void setVisible(boolean s) {this.show = s;}

}
